// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtuvy4vdFGhC0CJGDWnyqj7mt8cUjxges',
    appId: '1:247404803957:web:817bf225f0c3364f33053c',
    messagingSenderId: '247404803957',
    projectId: 'speakwise-258a0',
    authDomain: 'speakwise-258a0.firebaseapp.com',
    storageBucket: 'speakwise-258a0.appspot.com',
    measurementId: 'G-61B67XL5H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-jvInpap8oujI_pzUA_hWkY0G2tp11hc',
    appId: '1:247404803957:android:30563ab8a2c6caa333053c',
    messagingSenderId: '247404803957',
    projectId: 'speakwise-258a0',
    storageBucket: 'speakwise-258a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqCd5amNtNse5o-0aYAFE1BeWkIEKdzA',
    appId: '1:247404803957:ios:f0c9d2b47b0a025233053c',
    messagingSenderId: '247404803957',
    projectId: 'speakwise-258a0',
    storageBucket: 'speakwise-258a0.appspot.com',
    iosBundleId: 'com.example.speakwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqCd5amNtNse5o-0aYAFE1BeWkIEKdzA',
    appId: '1:247404803957:ios:46182ee8e567016a33053c',
    messagingSenderId: '247404803957',
    projectId: 'speakwise-258a0',
    storageBucket: 'speakwise-258a0.appspot.com',
    iosBundleId: 'com.example.speakwise.RunnerTests',
  );
}
